#167727746 user edit request
andela/storm-backend pull request #53
Opened 2019-09-09 17:25 UTC by kola-1

#### What this PR does
This PR will let a manager accept a trip request

#### Tasks completed
- add subrequest schema for the subrequest
- add request route to handle the request
- add subrequest route to handle subrequest
- add middleware to verify request editing authorization
- add updateTripRequest controller to update request

#### How this can be manually tested
- Clone this branch
- Change directory into it
- Run `npm install` in your terminal to install all the dependencies
- Add all the environment variables as specified in the `.env.config` file
- Run `npm run seed` in your terminal to seed the database
- Run `npm run start:dev` in your terminal to start the development server
- Test with postman or go to this URL to test with swagger `http://localhost:3000/api/v1/docs`
- Sign in as a user using this details `email: brucewayne@gmail.com, password: brucewayne`
- Send a put request with your request to be updated to `localhost:3000/api/v1/requests/edit/0fcda9b7-e17f-4162-88ed-ded031063e53` to test the request endpoint
- Send a put request with your subrequest to be updated to `localhost:3000/api/v1/subrequests/edit/01282bdb-e23f-4ece-ab08-49a1f618e66a` to test the subrequest endpoint

#### What are the relevant pivotal tracker stories?
[ #167727746](https://www.pivotaltracker.com/story/show/167727746)

2019-09-10 12:03 UTC, tejiri4 commented
Try your PR on heroku using the review app and add a comment if your endpoint is working on heroku

2019-09-10 13:02 UTC, jsbuddy requested changes

2019-09-10 13:02 UTC, jsbuddy commented on src/controllers/requestController.js
> +    const { requestType } = req;
Line 174 and 175 can be reduced to one line. Something like this `const { requestType, params: { requestId } } = req`

2019-09-10 13:02 UTC, jsbuddy commented on src/controllers/requestController.js
> +    const updatedRequest = await update(model, req.body, options);
Consider destructuring `body` and rename it to `data` from the `req` object on line 175.

2019-09-10 13:02 UTC, jsbuddy commented on src/middlewares/requestMiddlewares.js
> +    const { requestId } = req.params;
Line 34 and 35 can be reduced to one line, check previous comment above.

2019-09-10 20:21 UTC, kola-1 commented on src/controllers/requestController.js
> +    const { requestType } = req;
Done, thanks

2019-09-11 07:52 UTC, tejiri4 commented on src/routes/api/request.js
> +      checkToken,
why is backlisted middleware not here?

2019-09-11 07:53 UTC, tejiri4 commented on src/routes/api/request.js
> +      validate(requestIdSchema),
why is blacklisted middleware not here

2019-09-11 09:40 UTC, tejiri4 approved these changes
LGTM

2019-09-11 09:40 UTC, merged